### ISSUE TITLE
Subsequent megaport_partner_port data source fails to find ports

### ISSUE THREAD

**Issue by jaime-murillo** [utilitywarehouse/terraform-provider-megaport#1]
Hello,

First off Thank you for not only writing this provider, but making it public.

### Behavior
The issue that I am seeing is on the first _terraform apply_, the **megaport_partner_port** data resource is able to find available ports. On subsequent runs, it is returning an error.

```
Error: No ports were found. You might want to use a less specific query.

  on virtual_cross_connect.tf line 17, in data "megaport_partner_port" "main":
  17: data "megaport_partner_port" "main" {



Error: No ports were found. You might want to use a less specific query.

  on virtual_cross_connect.tf line 17, in data "megaport_partner_port" "main":
  17: data "megaport_partner_port" "main" {
```
### What I think is happening
I think this is due to the behavior of the Megaport API and the https://api.megaport.com/v2/secure/google/GCP_PAIRING_KEY endpoint. 

On the initial run, after provisioning the **megaport_port** port, the GCP pairing key is valid and the request for **megaport_partner_port** data resource is able to find the corresponding partner port. The **megaport_gcp_vxc** resource is created and configured.

```
{
  "message": "Successful lookup",
  "terms": "This data is subject to the Acceptable Use Policy https://www.megaport.com/legal/acceptable-use-policy",
  "data": {
    "bandwidths": [
      50,
      100,
      200,
      300,
      400,
      500,
      1000,
      2000,
      5000,
      10000
    ],
    "resource_type": "csp_connection",
    "megaports": [
      {
        "portSpeed": 10000,
        "name": "New York (lga-zone1-16)",
        "state": "NY",
        "description": "Google Inc at Digital Realty NYC2",
        "productUid": "11111111-1111-1111-1111-111111111111",
        "nServiceId": 11111,
        "companyUid": "11111111-1111-1111-1111-111111111111",
        "country": "USA",
        "vxc": null,
        "port": 11111,
        "companyName": "Google Inc",
        "locationId": 11,
        "productId": 11111,
        "companyId": 11
      },
      .
      .
      .
      {
        "portSpeed": 10000,
        "name": "Seattle (sea-zone1-86)",
        "state": "WA",
        "description": "Google Inc at Equinix SE2",
        "productUid": "11111111-1111-1111-1111-111111111111",
        "nServiceId": 11111,
        "companyUid": "11111111-1111-1111-1111-111111111111",
        "country": "USA",
        "vxc": null,
        "port": 11111,
        "companyName": "Google Inc",
        "locationId": 11,
        "productId": 11111,
        "companyId": 11
      }
    ]
  }
}
```

On subsequent runs, the GCP pairing key is no longer valid, so the request for **megaport_partner_port** data resource fails, as there is no longer a corresponding port. The Megaport API returns an empty megaports object.

```
{
  "message": "Successful lookup",
  "terms": "This data is subject to the Acceptable Use Policy https://www.megaport.com/legal/acceptable-use-policy",
  "data": {
    "csp_name": "Google",
    "connectType": "GOOGLE",
    "resource_type": "csp_connection",
    "bandwidth": 1000,
    "bandwidths": [
      50,
      100,
      200,
      300,
      400,
      500,
      1000,
      2000,
      5000,
      10000
    ],
    "pairingKey": "GCP_PAIRING_KEY",
    "megaports": []
  }
}
```

This runs in to the _len(filtered) < 1_  check in the _filterCloudPartnerPorts_ function and throws the error.

The documentation does NOTE this behavior, but the response from the https://api.megaport.com/v2/secure/google/GCP_PAIRING_KEY looks like an empty megaports object is a valid response for GCP VXC that has already been set up.

### Expected Behavior
**megaport_partner_port** data source should work with both new and existing ports.

### Workarounds
I have gotten around this by having the _len(filtered) < 1_ check in the _filterCloudPartnerPorts_ return an _api.MegaportCloud_ object with the _ProductUid_ set and added a lifecycle stanza to ignore **b_end** changes to the megaport_gcp_vxc resource.

**Comment by alkar** [comment]
Hi @jaime-murillo thank you for submitting this issue!

I've actually noticed the behaviour myself and I'm talking to Megaport about a safe way to work around this.

What I have found is that if you use a random UUID to perform the query (for which the probability that it is already used would be infinitesimal) it works as you would expect it. However, I have decided not to commit anything until I have verified that this approach will not produce any unwanted side effects.

I'll update this ticket once I know more.

**Comment by alkar** [comment]
After consideration, we've decided to merge the above and release a new rc. This should address the problem mentioned above. Can you please check and let me know how it looks? Thanks.

**Comment by jaime-murillo** [comment]
LGTM

**Comment by alkar** [comment]
Thanks for submitting this. Should be resolved now.
